------------------------------------------------------------------------------------------------------------------------
------------------------------- TABLES
------------------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS USERS (
  USER_ID         VARCHAR(100) NOT NULL PRIMARY KEY,
  FIRST_NAME      VARCHAR(50),
  LAST_NAME       VARCHAR(50),
  PASSWORD        VARCHAR(100),
  EMAIL_ADDRESS   VARCHAR(50) NOT NULL,
  USER_GROUP      VARCHAR(50) DEFAULT 'default' CHECK(USER_GROUP in ('admin'/*ADMIN*/, 'default' /*Normal User*/)),
  DATE_CREATED    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DATE_LAST_LOGIN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  IS_VERIFIED     BOOLEAN DEFAULT FALSE,
  IMAGE_URL       VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS CATEGORIES (
  NAME          VARCHAR(100) NOT NULL PRIMARY KEY,
  URL           VARCHAR(100),
  IMAGE_BYTES   BYTEA
);

CREATE TABLE IF NOT EXISTS EVENTS (
  EVENT_ID        VARCHAR(100) NOT NULL PRIMARY KEY,
  EVENT_NAME      VARCHAR(100),
  ADDRESS         VARCHAR(100),
  DESCRIPTION     TEXT,
  CATEGORY        VARCHAR(100) REFERENCES CATEGORIES(NAME),
  USER_ID_CREATED VARCHAR(100) REFERENCES USERS(USER_ID),
  LAT             DOUBLE PRECISION,
  LNG             DOUBLE PRECISION,
  IS_PUBLIC       BOOLEAN DEFAULT FALSE,
  START_TIME      TIMESTAMP,
  END_TIME        TIMESTAMP
);


CREATE TABLE IF NOT EXISTS MESSAGES (
  MESSAGE_ID      VARCHAR(100) NOT NULL PRIMARY KEY,
  MESSAGE_VALUE   TEXT,
  USER_ID_FROM    VARCHAR(100) REFERENCES USERS(USER_ID),
  USER_ID_TO      VARCHAR(100) REFERENCES USERS(USER_ID),
  DATE_SENT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);